# Generated by Django 6.0 on 2025-12-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сar_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000000)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
