# Generated by Django 6.0 on 2025-12-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_сar_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сar_brand',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
