# Generated by Django 6.0.2 on 2026-02-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0007_producttype_alter_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='category',
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model_app.source'),
        ),
    ]
