# Generated by Django 6.0.2 on 2026-02-24 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0008_remove_type_category_source_type_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_app.type'),
        ),
        migrations.RemoveField(
            model_name='type',
            name='source',
        ),
        migrations.CreateModel(
            name='ProductSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_app.product')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_app.source')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
