# Generated by Django 6.0.2 on 2026-02-26 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0009_alter_product_type_remove_type_source_productsource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='sourceType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model_app.sourcetype'),
        ),
    ]
