# Generated by Django 6.0.2 on 2026-03-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0010_sourcetype_source_sourcetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='productsource',
            name='name',
        ),
    ]
